services:
  postgres:
    image: postgres:15-alpine
    container_name: go-clean-template-db
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app_db"]

  redis:
    image: redis:7-alpine
    container_name: go-clean-template-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  api:
    build:
      context: ..
      dockerfile: build/Dockerfile
      target: development
    container_name: go-clean-template-api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - ../:/app
      - go_modules:/go/pkg/mod
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
  go_modules: