basePath: /api/v1
definitions:
  handlers.HealthResponse:
    properties:
      checks:
        additionalProperties:
          type: string
        type: object
      service:
        type: string
      status:
        type: string
      timestamp:
        type: string
      uptime:
        type: string
      version:
        type: string
    type: object
  handlers.SystemInfoResponse:
    properties:
      go_version:
        type: string
      memory:
        additionalProperties:
          type: integer
        type: object
      num_cpu:
        type: integer
      num_goroutine:
        type: integer
      service:
        type: string
      status:
        type: string
      timestamp:
        type: string
      uptime:
        type: string
      version:
        type: string
    type: object
info:
  contact:
    email: support@example.com
    name: API Support
  description: A Go API template built with Clean Architecture and Domain-Driven Design
    (DDD) principles.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Go Clean Architecture API
  version: "1.0"
paths:
  /health:
    get:
      description: Returns the basic health status of the service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.HealthResponse'
      summary: Get health status
      tags:
      - Health
  /heartbeat:
    get:
      description: Returns a simple heartbeat response to verify service is alive
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get heartbeat
      tags:
      - Health
  /live:
    get:
      description: Checks if the service is alive and responding
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.HealthResponse'
      summary: Get liveness status
      tags:
      - Health
  /ready:
    get:
      description: Checks if the service is ready to serve requests by verifying dependencies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.HealthResponse'
      summary: Get readiness status
      tags:
      - Health
  /system:
    get:
      description: Returns detailed system information including memory usage, CPU
        count, and runtime stats
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SystemInfoResponse'
      summary: Get system information
      tags:
      - Health
schemes:
- http
- https
swagger: "2.0"
